version: '3.8'

services:
  postgres-uat:
    build: .
    container_name: zuugle-postgres-uat
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: zuugle_suchseite_db
      POSTGRES_USER: zuugle_suche
      POSTGRES_PASSWORD: docker

  postgres-dev:
    build: .
    container_name: zuugle-postgres-dev
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: zuugle_suchseite_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
